### ISSUE TITLE
Arrow parser rejects pathlib.Path inputs: AttributeError: 'PosixPath' object has no attribute 'seek'

### ISSUE THREAD

**Issue by Haigutus** [Haigutus/triplets#75]
## Summary

With `triplets[arrow]` 0.1.0, passing `pathlib.Path` objects to `pandas.read_RDF()` fails. The same call works with plain `triplets` 0.1.0 (non-arrow parser) and with 0.0.17, so this is a regression in the accelerated parser's input handling.

## Reproduce

```python
from pathlib import Path
import pandas, triplets

pandas.read_RDF([Path("20220615T2230Z__Svedala_EQ_1.xml")])
```

```
File "triplets/parser/__init__.py", line 135, in parse
    results = [_one(f) for f in xml_files]
File "triplets/parser/__init__.py", line 129, in _one
    return parse_one(f, debug=debug)
File "triplets/parser/cython_pugixml_arrow.pyx", line 312, in triplets.parser.cython_pugixml_arrow.load_rdf_to_dataframe
AttributeError: 'PosixPath' object has no attribute 'seek'
```

Environment: triplets 0.1.0 with `[arrow]` extra, Python 3.13, Linux.

## Cause

`load_rdf_to_dataframe` in `cython_pugixml_arrow.pyx` (around line 312) appears to branch on `isinstance(input, str)` and treats everything else as a file-like object, calling `.seek()` on it. `pathlib.Path` is neither, so it crashes.

## Suggested fix

Coerce path-like inputs before the file-like branch, e.g.:

```python
import os
if isinstance(f, (str, os.PathLike)):
    f = os.fspath(f)
```

Workaround: pass `str(path)` (this is what cim-bench does now).

Found while benchmarking triplets 0.1.0 in https://github.com/Haigutus/cim-bench.

**Comment by Haigutus** [comment]
Related path regression in the same release, on the **export** side:

With 0.1.0, the in-memory file objects returned by `export_to_cimxml` carry **absolute, source-derived** `.name` values (e.g. `/benchmarks/data/.../20220615T2230Z__Svedala_EQ_1.zip` — note it is derived from where the *input* files were loaded from). The save loop then does:

```python
export_path = os.path.join(export_base_path, file_object.name)   # export/__init__.py ~line 354
```

`os.path.join` discards `export_base_path` entirely when the second argument is absolute, so exports are written **next to the source data** instead of into `export_base_path`:

```
OSError: [Errno 30] Read-only file system: '/benchmarks/data/relicapgrid/Instance/Grid/IGM_Svedala/20220615T2230Z__Svedala_EQ_1.zip'
```

(Data is mounted read-only in the benchmark containers, which surfaced it.) Datasets loaded from a ZIP are unaffected — their exported names are relative — it hits datasets loaded from plain XML files.

Suggested fix: keep `file_object.name` relative (just the basename), or guard the join with `os.path.basename` when `export_base_path` is set.

Workaround used in cim-bench: `export_to_memory=True` and writing `output_dir / Path(f.name).name` manually.
